baseURL: https://m0ka.it/
languageCode: en-us
build:
  writeStats: true
params:
  title: Moka's resume
  author: Ciro Ogliastro
  description: Moka resume
  copyright:
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: true
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Ciro Ogliastro"
    tagline:
    location: ""
    photo: fp.jpg
  social:
    title: Links
    list:
      - icon: fab fa-github
        url: "https://github.com/moka-co"
        title: GitHub
      - icon: fab fa-twitter
        url: "https://twitter.com/m0ka_co"
        title: Twitter
      #- icon: fab fa-orcid
      #  url: "#"
      #  title: Orcid
      #- icon: ai ai-google-scholar
      #  url: "#"
      #  title: Google Scholar
      #- icon: fab fa-researchgate
      #  url: "#"
      #  title: ResearchGate
  showInAccordion:
    - item: aboutme
      expand: true
    - item: education
    #- item: publication
    - item: project
    - item: experience
    #- item: skill
    #- item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: "I'm currently pursuing a Master's degree in Machine Learning & Big Data at Università degli Studi di Napoli \"Parthenope\". I'm interested in Artificial Intelligence, Infosecurity and privacy. I'm part of \"Etica Digitale\", a divulgative project on technology and human rights"
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Curricular Intership
        dates: May 2023 - November 2023
        company: Accenture
        details: |1-
          - Developed a Cyberattack protection asset integrated into the applications of Java-based web applications
          - Work done was furthered with an experimental thesis on Machine Learning to identify Cross-Site Scripting attacks attempts
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: B.S. in Computer Science
        college: Università degli Studi di Napoli "Parthenope"
        thesis_title: "Machine Learning for Cross-Site Scripting Attack Detection (experimental thesis)​"
        dates: September 2019 - January 2024
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Etica Digitale
        url: "https://eticadigitale.org/"
        description: "Divulgative project on technology and human rights"
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "Skill 1, Skill 2"
        skillrating: 90
      - skill: Skill 3
        skillrating: 80
      - skill: Skill 4
        skillrating: 50
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Cooking
      - hobby: Hiking
      - hobby: Baking
